### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by Bujiraso** [anduchs/audio-output-switcher#20]
I noticed that this project lacks license definitions within file or on the project level.

If @anduchs could please choose and add a license so that others may (or will know not to) build upon it in the appropriate fashion, I would be grateful.

Thanks!

**Comment by Bujiraso** [comment]
Hey @anduchs, did you want to add a license to this code-base, while you're tidying up loose ends on it? Technically being your code, I think you have the most right to decide one.

**Comment by anduchs** [comment]
Done
